### ISSUE TITLE
Allow underscore patterns to be named.

### ISSUE THREAD

**Issue by allanderek** [gren-lang/compiler#111]
As we know, `_` is used to mean `ignore this value` in a pattern, sometimes in a `case` expression, sometimes as one of the arguments to a function.

Haskell, and I think a few others, allow you to spell this as `_` followed by any valid unqualified identifier.

This allows something like the following:
```elm
sumDict : Dict comparable Int -> Int
sumDict =
    Dict.foldl (\_key value -> total = value + total) 
```
or
```elm
sumDict : Dict comparable Int -> Int
sumDict =
    let
          add : comparable Int -> Int -> Int
          add _key value total =
               value + total
    in
    Dict.foldl add
```

I've always personally quite liked this. I like that it says something like "I'm ignoring the key here", as opposed to "I'm ignoring something".

One possible downside is that such names can become misleading after the thing that is matched is changed.

**Comment by robinheghan** [comment]
Solved
