### ISSUE TITLE
Why no mention of elm?

### ISSUE THREAD

**Issue by rtorr** [gren-lang/compiler#168]
Seems kind of odd for it not to mention this in the readme.

**Comment by robinheghan** [comment]
It's mentioned on the website.

As Gren cannot compile Elm code, and doesn't intend to be compatible with Elm in any way, I don't really see any reason to draw more attention to the fact that Gren was forked from Elm.

Forking from Elm was mostly done to save time.

**Comment by robinheghan** [comment]
> Because giving credit for others work is just a decent thing to do?

Agreed, which is also why:

* Elm is mentioned in the Gren Programming Book: https://gren-lang.org/book/faq.html
* Elm is mentioned in the Gren 0.1 release announcement: https://gren-lang.org/news/220530_first_release
* The git history of every repo ported from Elm is left as-is (even though it would've been helpful to squash all pre-gren commits into one).

But adding a mention of Elm to the readme would, I think, only cause confusion. If my first impression of a language is that it's a fork of some other language, I would expect a certain level of compatibility at the language and implementation level. That is, however, not the case. It's not a goal of the Gren project to remain compatible, in any way whatsoever, with Elm.
