### ISSUE TITLE
Improvements to git based package manager

### ISSUE THREAD

**Issue by robinheghan** [gren-lang/compiler#18]
While we have a working new package manager, it could stand some improvements:

* Perform fewer git operations that crosses the network.
* Be smarter about logging
* Review the file locking mechanism. Are we using it in all the right places?
* Revise messages presented to the user
* Fallback to SSL if HTTPS fails.
* Should `make` provide error if a package is missing? Only `install` should perform package downloads.
* Allow override to use SSL/HTTPS (which one should be default?)

**Comment by joakin** [comment]
At work we have a huge repo and when we clone it for dev initially it is recommended to do a [shallow clone](https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt) with `--depth=1` which speeds the cloning operation significantly. 

I know with shadow clones you can fetch specific branches with just the last commit, and it should also be possible to fetch all branch tips using explicitly `--no-single-branch`.

So in the end something like this: `git clone --branch mytag0.1 --depth 1 --no-single-branch https://example.com/my/repo.git`

I don't know if Gren already does this but if it doesn't it may be a great way to speed up the package manager downloads.

**Comment by robinheghan** [comment]
Gren doesn’t do this right now, because it wasn’t immedietly clear to me how retrieving now tags would work.

I’ll definetly look into it for 0.2.0 though 👍

**Comment by robinheghan** [comment]
Improvements made in PRs: #135, #138, #126, #83, #87 and #88
