### ISSUE TITLE
Support the NO_COLOR standard for omitting color from CLI

### ISSUE THREAD

**Issue by robinheghan** [gren-lang/compiler#207]
It's all in the standard: http://no-color.org/

**Comment by aboeglin** [comment]
The title makes it sound like adding a cli flag. I think it’d be better to directly use the environment variable and try to support the emerging standard, what do you think?

**Comment by robinheghan** [comment]
Agreed. Edited the title, is that better?

**Comment by aboeglin** [comment]
Definitely!
