### ISSUE TITLE
Are optimizations working?

### ISSUE THREAD

**Issue by ii8** [gren-lang/compiler#229]
Using the --optimize flag doesn't appear to make any difference to the output.

**Comment by robinheghan** [comment]
`--optimize` mostly mangles property names in records. Like

```js
{ name: "String
, age: 10
}
```

Will instead be compiled to

```js
{ a:"String", b:10 }
```

The idea is that it performs optimizations that would be difficult for a minifier to do.

**Comment by ii8** [comment]
What I mean is, if I have a simple example Main.gren with a few records with long names
And I run
```
gren make --output=a.js Main.gren
gren make --output=b.js --optimize Main.gren
diff a.js b.js
```
It reports there is no difference. Is that expected? What does optimize do in that case?
