### ISSUE TITLE
Ability to integrate with template engines.

### ISSUE THREAD

**Issue by nacho00112** [gren-lang/compiler#236]
Examples are [jinja](https://github.com/pallets/jinja) or [web.py's templator](https://webpy.org/docs/0.3/templetor)
those are python because I use python.
Adding some sort of feature to embed the syntax of template engines should be enough.

**Comment by robinheghan** [comment]
It's rare for languages to support templating directly, and I also consider it to be a bad fit for Gren specifically.

The right approach here would be to generate Gren code from a template, or make a Gren package that understands a specific template language.

I'm not against templating languages, but I don't think the language should have explicit support for it.
