### ISSUE TITLE
gren compiler terminates with ParseProblem

### ISSUE THREAD

**Issue by aramiscd** [gren-lang/compiler#275]
I'm on Ubuntu Linux:

```shell
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

I downloaded gren 0.5.2 und put it in my `$PATH`:

```
$ wget https://github.com/gren-lang/compiler/releases/download/blob-0.5.2/gren_linux
$ chmod +x gren_linux
$ mv gren_linux ~/.local/bin/gren0.5.2
```

First, I tried to print the version:

```$ gren0.5.2 --version
gren0.5.2: ParseProblem "--version" (Start 1 1)
CallStack (from HasCallStack):
  error, called at terminal/Main.hs:37:17 in main:Main
```

I was expecting this to print `0.5.2`.

When I try to compile something, I get a similar error:

```
$ gren0.5.2 src/Main.gren 
gren0.5.2: ParseProblem "src/Main.gren" (Start 1 1)
CallStack (from HasCallStack):
  error, called at terminal/Main.hs:37:17 in main:Main
```

The file is there and contains gren 0.4.5 code.  I was expecting this to throw a few errors related to the code.

**Comment by robinheghan** [comment]
With 0.5.0 onwards, the compiler is split in two parts. There's a part written in Gren, which is compiled to JS, which executes the Haskell based compiler.

You've only downloaded the Haskell based part of the compiler, you still need the Gren-based one.

**Comment by aramiscd** [comment]
I see.  `npm install -g gren-lang` did the trick.  I should have rtfm then.  My apologies!
