### ISSUE TITLE
Add commands for managing dependencies

### ISSUE THREAD

**Issue by robinheghan** [gren-lang/compiler#48]
It would be nice to offer commands for removing and updating the dependencies of a project.

- [ ] `gren remove`
- [ ] `gren outdated [ --upgrade ]`

**Comment by atlewee** [comment]
> Also across all the different package manager tools I use, it's confusing to remember which uses "remove" vs "uninstall", so maybe having them both as aliases for the same thing would be nice.

But then again, people writing tutorial's and readme's for gren will probably use a mix of both.
That may be confusing for new users.?
A nice thing I love about elm is that there is less ways to do the same thing than other languages :)
