### ISSUE TITLE
Array.sortBy does not compile

### ISSUE THREAD

**Issue by atlewee** [gren-lang/compiler#73]
Looks like the compiler needs "sortBy-function-return-value" to match the type of the items in Array.
![image](https://user-images.githubusercontent.com/11732817/171992820-967f9c1a-166d-4a45-87c2-d96c9bb7d76c.png)

**Comment by robinheghan** [comment]
Actually, this is a bug with the type annotation of Array.sortBy, not the compiler.

**Comment by atlewee** [comment]
Wow, fast reply.
Yea I saw that after looking at the old List implementation. sorry for registering at the wrong place :)
